// Mocks generated by Mockito 5.4.6 from annotations
// in brain_forge_movies/test/features/dashboard/data/repositories/dashboard_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:brain_forge_movies/core/network/network_info.dart' as _i5;
import 'package:brain_forge_movies/features/dashboard/data/datasources/dashboard_remote_datasource.dart'
    as _i2;
import 'package:brain_forge_movies/features/dashboard/data/models/movie_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DashboardRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRemoteDataSource extends _i1.Mock
    implements _i2.DashboardRemoteDataSource {
  @override
  _i3.Future<List<_i4.MovieModel>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i3.Future<List<_i4.MovieModel>>.value(
              <_i4.MovieModel>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i4.MovieModel>>.value(
              <_i4.MovieModel>[],
            ),
          )
          as _i3.Future<List<_i4.MovieModel>>);

  @override
  _i3.Future<List<_i4.MovieModel>> getMovie(String? movieName) =>
      (super.noSuchMethod(
            Invocation.method(#getMovie, [movieName]),
            returnValue: _i3.Future<List<_i4.MovieModel>>.value(
              <_i4.MovieModel>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i4.MovieModel>>.value(
              <_i4.MovieModel>[],
            ),
          )
          as _i3.Future<List<_i4.MovieModel>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
